name: Build apk for development test
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Flutter build apk for development test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java SDK 12
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    - name: Setup Flutter Environment
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --release
      env:
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS: ${{ secrets.ALIAS }}
        KEY_PATH: key.jks
    - name: Create a Release APK for development testing
      uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk