name: Build aab for playstore release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Flutter build release aab
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java SDK 12
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    - name: Setup Flutter Environment
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build appbundle
      env:
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS: ${{ secrets.ALIAS }}
        KEY_PATH: key.jks
    - name: Create a Release AppBundle for PlayStore
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ secrets.VERSION }}
        artifacts: "build/app/outputs/bundle/release/*.aab"
        token: ${{ secrets.TOKEN }}
